name: Create Firestore Database Quarterly

on:
  schedule:
    - cron: '30 5 1 1,4,7,10 *'
  workflow_dispatch:

jobs:
  create-firestore:
    name: 'Create Google Cloud Firestore Database'
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # --- مرحله جدید برای اشکال‌زدایی ---
      - name: 'Debug Secrets'
        run: |
          if [ -z "${{ secrets.GCP_WIF_PROVIDER }}" ]; then
            echo "ERROR: GCP_WIF_PROVIDER secret is NOT set or is empty!"
            exit 1
          else
            echo "SUCCESS: GCP_WIF_PROVIDER secret is set."
          fi

          if [ -z "${{ secrets.GCP_SA_EMAIL }}" ]; then
            echo "ERROR: GCP_SA_EMAIL secret is NOT set or is empty!"
            exit 1
          else
            echo "SUCCESS: GCP_SA_EMAIL secret is set."
          fi
      # --- پایان مرحله اشکال‌زدایی ---

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: 'Create Firestore Database'
        run: |
          gcloud beta firestore databases create \
            --location="YOUR_DATABASE_LOCATION" \
            --project="${{ secrets.GCP_PROJECT_ID }}"
        continue-on-error: true

      - name: Check creation status
        run: |
          echo "Firestore database creation command executed. If a database already existed, the previous step would have failed gracefully."
          echo "You can check the status in your Google Cloud console."
